# GitHub Actions
# This workflow will prepare the testing environment and run test cases

name: Django Backend Test

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f optional-requirements.txt ]; then pip install -r optional-requirements.txt; fi
    - name: Copy settings file
      run: cp ./npsat_backend/local_settings_template.py ./npsat_backend/local_settings.py
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: python manage.py test
